# Generated by Django 3.0.6 on 2020-05-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
